export const SITE = {
  website: "https://dimpemekug.com/",
  author: "dimpemekug",
  profile: process.env.PUBLIC_SOCIAL_GITHUB ?? "",
  desc: "App e siti web. Codice pulito, idee chiare.",
  title: "dimpemekug.com",
  ogImage: "devosfera-og.webp",
  lightAndDarkMode: true,
  postPerIndex: 6,
  postPerPage: 12,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showGalleries: false,
  showGalleriesInIndex: false,
  showBackButton: true,
  showTagsInCards: true,
  showCoverImages: false,
  indexPostsGrid: false,
  heroTerminalPrompt: {
    prefix: "~",
    suffix: "$",
  },
  backdropEffects: {
    cursorGlow: true,
    grain: true,
  },
  editPost: {
    enabled: false,
    text: "Edit this post",
    url: process.env.PUBLIC_EDIT_POST_URL ?? "",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "it",
  timezone: "Europe/Rome",
  introAudio: {
    enabled: false,
    src: "https://fluxfm.streamabc.net/flx-chillhop-mp3-128-8581707",
    isStream: true,
    label: "LOFI",
    duration: 30,
  },
} as const;
